disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Brain Boosters!"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Rhian Poole"
   # email = "youremail@example.com"
   image = "img/brainboosters.jpeg"
   imageQuality = 96
   headline = "Empowering Learners, Supporting Families – Tailored Tuition, Creative Learning & Expert SEND Consultancy"

