disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Brain Boosters | Private Tutoring in Ealing (KS1–KS4)"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "One-to-one Maths, English, Science and SEND-friendly tutoring in Ealing (W5). QTS-qualified, DBS-checked. Calm, structured lessons online or in West London."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Brain Boosters"
   # email = "youremail@example.com"
   image = "img/brainboosters.jpeg"
   imageQuality = 96
   headline = "Empowering Learners, Supporting Families – Tailored Tuition, Creative Learning & Expert SEND Consultancy"

